---
title: "childlessness-in-america"
author: Mehrnoush Mohammadi
thanks: "Code and data are available at: https://github.com/mehrnoush68/childlessness-in-america.git"
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
library(knitr)
library(kableExtra)
library(here)
library(ggplot2)
library(formattable)

```


# Introduction



# Data {#sec-data}



```{r}
#| echo: false
#| include: true
#| warning: false
#| label: nochild_age_graph

table_nochild_age <-
  read_csv(
    file = "../data/clean_data_age.csv",
    show_col_types = FALSE
  )

nochild_age_data_long <- tidyr::pivot_longer(table_nochild_age, -age, names_to = "year", values_to = "percentage")

ggplot(nochild_age_data_long, aes(x = as.integer(year), y = percentage, color = age)) +
  geom_line() +
  labs(x = "Year", y = "Percentage", title = "Percentage over Time by Age Group", color = "Age Group") +
  theme_minimal()

```

```{r}
#| echo: false
#| include: true
#| warning: false
#| label: nochild_class_graph

table_nochild_class <-
  read_csv(
    file = "../data/clean_data_class.csv",
    show_col_types = FALSE
  )

# Pivot the data from wide to long format
data_long <- pivot_longer(table_nochild_class, -`Class Identification`, names_to = "Year", values_to = "Percentage")

# Convert Year column to integer
data_long$Year <- as.integer(data_long$Year)

# Plot the data
ggplot(data_long, aes(x = Year, y = Percentage, color = `Class Identification`)) +
  geom_line() +
  labs(x = "Year", y = "Percentage", title = "Percentage over Time by Class", color = "Breakdown Category") +
  theme_minimal()

```


```{r}
#| echo: false
#| include: true
#| warning: false
#| label: nochild_degree_graph

table_nochild_degree <-
  read_csv(
    file = "../data/clean_data_degree.csv",
    show_col_types = FALSE
  )

# Pivot the data from wide to long format
data_long <- pivot_longer(table_nochild_degree, -`Degree`, names_to = "Year", values_to = "Percentage")

# Convert Year column to integer
data_long$Year <- as.integer(data_long$Year)

# Plot the data
ggplot(data_long, aes(x = Year, y = Percentage, color = `Degree`)) +
  geom_line() +
  labs(x = "Year", y = "Percentage", title = "Percentage over Time by Higest Degree", color = "Degree") +
  theme_minimal()

```

```{r}
#| echo: false
#| include: true
#| warning: false
#| label: nochild_gender_graph

table_nochild_sex <-
  read_csv(
    file = "../data/clean_data_sex.csv",
    show_col_types = FALSE
  )

# Pivot the data from wide to long format
data_long <- pivot_longer(table_nochild_sex, -`Gender`, names_to = "Year", values_to = "Percentage")

# Convert Year column to integer
data_long$Year <- as.integer(data_long$Year)

# Plot the data
ggplot(data_long, aes(x = Year, y = Percentage, color = `Gender`)) +
  geom_line() +
  labs(x = "Year", y = "Percentage", title = "Percentage over Time by Gender", color = "Gender") +
  theme_minimal()

```





# Results


# Discussion

## First discussion point {#sec-first-point}

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# References


